### ISSUE TITLE
Bugreport: incomplete range analysis on clang 

### ISSUE THREAD

**Issue by gnzlbg** [gergo-/missed-optimizations#1]
I've filled [a bug report](https://bugs.llvm.org/show_bug.cgi?id=34517) for the incomplete range analysis on clang. Thanks for doing this.

**Comment by gergo-** [comment]
Thanks for filing the report! Since I already have a number of open issues and a pending patch, I stopped reporting to avoid spamming the bug tracker. We'll see where this goes.

**Comment by gergo-** [comment]
Come to think of it, I should add a note that you filed a report. I will do that now. Feel free to open a pull request with a little note if you decide to report something else. Thanks again!
